//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaslnySecurity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class webpages_UserPermissions
    {
        public int UserPageId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<bool> CanRead { get; set; }
    
        public virtual User User { get; set; }
        public virtual webpages_Pages webpages_Pages { get; set; }
    }
}
