//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaslnyLib.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditDetailsView
    {
        public int AuditTrialID { get; set; }
        public int EntityID { get; set; }
        public string EntityName { get; set; }
        public int ActionTypeID { get; set; }
        public string ActionTypeName { get; set; }
        public int ActionID { get; set; }
        public string ActionName { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public string EntityRecord { get; set; }
    }
}
