//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaslnyLib.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CarMaintenance
    {
        public int CarMaintenanceID { get; set; }
        public int CarID { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public System.DateTime CarMaintenanceDate { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public string CarMaintenanceDetails { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public bool IsDeleted { get; set; }

        public virtual Car Car { get; set; }
    }
}
