//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaslnyLib.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Trips = new HashSet<Trip>();
        }
    
        public int CustomerID { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public string CustomerFName { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public string CustomerLName { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public bool CustomerGender { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public string CustomerAddress { get; set; }

        [Required(ErrorMessage = "Please enter this Field"), MaxLength(11)]
        public string CustomerPhone { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public string CustomerCity { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Your Email is not valid.")]
        public string CustomerEmail { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public bool IsDeleted { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public System.DateTime CustomerDOB { get; set; }

        public bool IsUnderAge()
        {
            var age = DateTime.Today.Year - CustomerDOB.Year;
            if (age < 16) return true;
            else return false;
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
