//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaslnyLib.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.Trips = new HashSet<Trip>();
        }
    
        public int DriverID { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public string DriverFName { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public string DriverLName { get; set; }

        [Required(ErrorMessage = "Please enter this Field"), MaxLength(11)]
        public string DriverPhone { get; set; }

        [RegularExpression(@"^\d{14}$", ErrorMessage = "SSN must be exactly 14 digits.")]
        [Required(ErrorMessage = "Please enter this Field")]
        public long DriverSSN { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public float DriverSalary { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public System.DateTime DriverDOB { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public string DriverAddress { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public string DriverPhoto { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public string DriverCity { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public System.DateTime DriverLED { get; set; }

        public Nullable<System.DateTime> DriverLastTripDT { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public bool IsDeleted { get; set; }


        public bool IsLicenseExpired()
        {
            if (DriverLED <= DateTime.Now)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
