//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaslnyLib.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriversEvaluation
    {
        public string DriverFName { get; set; }
        public string DriverLName { get; set; }
        public string DriverPhone { get; set; }
        public System.DateTime DriverLED { get; set; }
        public string RouteTo { get; set; }
        public System.DateTime TripPredictedTravelDT { get; set; }
        public Nullable<int> TripDriverRating { get; set; }
        public string TripComments { get; set; }
        public long DriverSSN { get; set; }
        public float DriverSalary { get; set; }
        public System.DateTime DriverDOB { get; set; }
        public string DriverAddress { get; set; }
        public string DriverPhoto { get; set; }
        public string DriverCity { get; set; }
        public Nullable<System.DateTime> DriverLastTripDT { get; set; }
        public bool IsDeleted { get; set; }
        public bool Expr1 { get; set; }
        public int RouteID { get; set; }
        public int DriverID { get; set; }
        public int TripID { get; set; }
        public System.DateTime TripBookingDT { get; set; }
        public Nullable<System.DateTime> TripRealTravelDT { get; set; }
        public Nullable<System.DateTime> TripArrivalDT { get; set; }
        public Nullable<int> TripStartKM { get; set; }
        public Nullable<int> TripEndKM { get; set; }
        public int TripPassengers { get; set; }
        public string TripStatus { get; set; }
        public Nullable<int> TripCarRating { get; set; }
        public bool Expr2 { get; set; }
    }
}
