//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaslnyLib.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Price
    {
        public int PriceID { get; set; }
        public int RouteID { get; set; }
        public int CarClassificationID { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public float PriceMoney { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public bool IsDeleted { get; set; }

        public virtual CarClassification CarClassification { get; set; }
        public virtual Route Route { get; set; }
    }
}
