//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaslnyLib.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Trip
    {
        public int TripID { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public System.DateTime TripBookingDT { get; set; }
        public Nullable<System.DateTime> TripRealTravelDT { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public System.DateTime TripPredictedTravelDT { get; set; }
        public Nullable<System.DateTime> TripArrivalDT { get; set; }
        public Nullable<int> TripStartKM { get; set; }
        public Nullable<int> TripEndKM { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public int TripPassengers { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public string TripStatus { get; set; }
        public Nullable<int> TripDriverRating { get; set; }
        public Nullable<int> TripCarRating { get; set; }
        public string TripComments { get; set; }

        public int DriverID { get; set; }
        public int CarID { get; set; }
        public int RouteID { get; set; }
        public int CustomerID { get; set; }

        [Required(ErrorMessage = "Please enter this Field")]
        public bool IsDeleted { get; set; }

        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Route Route { get; set; }
    }
}
