//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaslnyLib.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WaslnyLibDbContext : DbContext
    {
        public WaslnyLibDbContext()
            : base("name=WaslnyLibDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Car>()
             .HasIndex(c => c.CarPN)
             .IsUnique();
            throw new UnintentionalCodeFirstException();

        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<ActionType> ActionTypes { get; set; }
        public virtual DbSet<AuditTrial> AuditTrials { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CarClassification> CarClassifications { get; set; }
        public virtual DbSet<CarMaintenance> CarMaintenances { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<MasterEntity> MasterEntities { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<AuditDetailsView> AuditDetailsViews { get; set; }
        public virtual DbSet<CarsEvaluation> CarsEvaluations { get; set; }
        public virtual DbSet<DriversEvaluation> DriversEvaluations { get; set; }
        public virtual DbSet<TripDetail> TripDetails { get; set; }
    }
}
